{% set version = '1.63-1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dynamictreecut
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dynamicTreeCut_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dynamicTreeCut/dynamicTreeCut_{{ version }}.tar.gz
  sha256: 831307f64eddd68dcf01bbe2963be99e5cde65a636a13ce9de229777285e4db9

build:
  number: 1007
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('dynamicTreeCut')"           # [not win]
    - "\"%R%\" -e \"library('dynamicTreeCut')\""  # [win]

about:
  home: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/BranchCutting/
  license: GPL-2.0-or-later
  summary: Contains methods for detection of clusters in hierarchical clustering dendrograms.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: dynamicTreeCut
# Version: 1.63-1
# Date: 2016-03-10
# Title: Methods for Detection of Clusters in Hierarchical Clustering Dendrograms
# Author: Peter Langfelder <Peter.Langfelder@gmail.com> and Bin Zhang <binzhang.ucla@gmail.com>, with contributions from Steve Horvath <SHorvath@mednet.ucla.edu>
# Maintainer: Peter Langfelder <Peter.Langfelder@gmail.com>
# Depends: R (>= 2.3.0), stats
# ZipData: no
# License: GPL (>= 2)
# Description: Contains methods for detection of clusters in hierarchical clustering dendrograms.
# URL: http://www.genetics.ucla.edu/labs/horvath/CoexpressionNetwork/BranchCutting/
# NeedsCompilation: no
# Packaged: 2016-03-10 18:25:27 UTC; plangfelder
# Repository: CRAN
# Date/Publication: 2016-03-11 00:39:02
