{% set version = "1.63-1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dynamictreecut
  version: {{ version|replace("-", "_") }}

source:
  fn: dynamicTreeCut_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dynamicTreeCut_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dynamicTreeCut/dynamicTreeCut_{{ version }}.tar.gz
  sha256: 831307f64eddd68dcf01bbe2963be99e5cde65a636a13ce9de229777285e4db9

build:
  noarch: generic
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('dynamicTreeCut')"  # [not win]
    - "\"%R%\" -e \"library('dynamicTreeCut')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/dynamicTreeCut/index.html
  license: GPL-2.0-or-later
  summary: Contains methods for detection of clusters in hierarchical clustering dendrograms.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
