travis:
  secure:
    BINSTAR_TOKEN: RDpbcPdyJRZSnuLtwO/E8uJVX8B1YGpQ1kIsvVg727kGxMj0JaBcTAYJI6rojszU8u+62ZMgou0iC3+pIglv5s4ZAWJsegbZ78eSIcVMODCxz62Cnw9E80vM7NCgvoNKo8OuJu/PXFmtYHAJfcM95aXuAU+IXScJTKJS6XLMpexov8xyDEINxpK6epEwL/yTcWFEvGoqvTfwb/gnLOOf3Sa/SpGTqgwRn6MrBhs3tDKwIvb6+3Gl/DwxLKclIH2tiaXIlppFwMGvYdQ7BwPov4X63w3kzUD45OZ8DwBOAvEm8DTLq54Zj8p55ACNxLaFAdYKP0mvTry77EslrhlAtLguhFaNBB3xo+LfXzLcy+s16o7FNf/AvTH2+neJ+d8YjyfdPN3zLJ/+p3y7N4Gy9h8KIX7ppvzl8lRPMzWuwQckFiirDPRMzabPzlo46sSIhfU8wG0n27AeHbzgym9TPrMhw5/nCZsyA0boTomNh0aw5l/gP/mYshwuh5FHd6pih9oNGd69ciBYYp0OK9FPYoWVtzBHhp7FsDtkQ+3bzvRiB1tphNEFXQ6ULhRhLDzQEXQQrzkAfAZ+JRFK49abZ26NIDwMCJaR6RQ9d54bdhQ9UatSGQmKYbn2nQ0oQI2YKs27A0Cah6m4dg1m7arbVsXFC+C4l8EZ/ekCd8iJE1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
