travis:
  secure:
    BINSTAR_TOKEN: h5Vmty2qOSEf/2qvF/X/AJB+FskhRGSzhFG69dYJPmkxypCWWo2rQwv9ijeG1yJKD+hv+Keh8IDrx6WIGCLgZXTu/kcCK7UkAyWq0GiN7E+SszhB5m4/Tk9CrZvAsPvpjaK9GCdTRoLhCKW7Hcs8lfQW2EPte7k78O17GGz6TeWKbrcFY01uQAex+5fj2xvomocbFmG2RGkhmddjZEwJ2VFj0vP1SQBBPSdSgN/Z/MyRYQ6ukOGQcrWAFOAWR80YX7hj7/lk9TwhrjmiVBA9YJJu6qsU7LDRMTHaVjzNVCx4oMHqr0MbTr8EaGfzbWsjG/h1SWOC4mECta2Vyw0qICRtqFJ6NxfPECllB9eWcG2mQCuzpuWDgoOx2eGNMYjLs0CanvhU6TVFLB3NFmeaPH6kCuaOc/24qeWCH6Pujroo+m/zm6Kk/GI2FusTwUAjnGVV6YmPab1Q044EQoxcC0kNBH6HVXYgQjba2TvlwKJuW269AzHIfAoS5fApohoWznEI5Pddo+WMxvBIVRUSkOH3KN8X1PL6NKRO/EFz+8gTOq0md9JvInoYBS8TMzL0K+fX5BprbYEsbMmUhQNt5AlujZehtG/MHmlEG64ZoKLDD5b8Jz+qAb469QZy+CnMAFNe/2ePAJzCXpqzqCKPd1olZVKukqITSTpbHaygz5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
