travis:
  secure:
    BINSTAR_TOKEN: PelTHytzBpFDFGXzTl620a91Vg6oWlZAp+G51H6UUBhwtLWNVPs4314QvI2jOloza7YvN6/Ef8wxOCblsaXN1zILCM49+8iGppQCzxFFrp105bUNN4jErqNp37EEl6hRPLsDtPY401L+PBR+mZg/Xm6wkdVMNpSDAl9mHmebi7M10sxn6aV4k0vrZR6O/jeMRs9zSdT1Gui8++BeJ3npg7RWcO8EcD/or8FPS1eeaO/BsqLjWg1obfnSmSMpWEt/f8bliGoemmaZ1Pf26+PRHNaOYN3t7enS+LRdh//RkqFkjGRvgnNvzVf7Uzd1c0kC5omSYLWwXF9T6yGzHDoYD4/t65GGd8/mUFdITs8EAmJOaqrXQCHdpq73pArfuAIzVjZ8b+UZP5y1DGlalAU5tRqirLd/JCw0dk+WCHPFLiF6xDGnUSvt7RTqaHakOgtsZKRxZ0V6csQuIGDfjI0kmA908Ip/fW7hxwXbKj3wgOlcevUJXvdA1d8Yi9/AiLNptye1b8Yvf7PP83j9eBLZPuyBsZ8KxmfyAUHCxBIvIHhvf8mQZi9DBADpSu+VzZOKUShoTL94kmXgiL2EJueuodrzOEsd7RtOhEsJH1RuoqSx/3FY7IlJDKb6J2OIuw5ji3OIEr4yT4g4lh8w15koMZliRlcKrUczTAHlyWEUkeI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
